export const lesson2 = {
  href: "/materials/ulleung-high-lesson-2",
  date: "2026-09-19",
  pdf: "/assets/materials/ulleung-high-2026-09-19.pdf",
  titles: [
    ["울릉의 아이디어를, 우리의 사업으로", "From Ulleung ideas to our business"],
    ["오늘의 결과 3가지", "Three outcomes for today"],
    ["오늘은 계획, 제작은 조사 후", "Plan today; make after research"],
    ["한 회사, 두 사업팀", "One company, two business teams"],
    ["게임 완성, 사업도 완성?", "A finished game, a finished business?"],
    ["아이디어 → 실행 → 개선", "Idea → action → improvement"],
    ["사업을 보는 4가지 질문", "Four questions about a business"],
    ["쓰는 사람, 사는 사람", "Users and buyers"],
    ["이 순간, 무엇이 필요할까?", "What is needed in this moment?"],
    ["게임이 남길 경험", "The experience a game offers"],
    ["지금 쓰는 대안은?", "What alternatives are used now?"],
    ["관심과 참여는 다른 근거", "Interest and participation are different evidence"],
    ["홍보의 목표는 어떤 행동?", "What action should promotion lead to?"],
    ["우리 힘으로 가능한가?", "Can we do it with our resources?"],
    ["매출 ≠ 이익", "Revenue is not profit"],
    ["인쇄비 밖의 비용", "Costs beyond printing"],
    ["할 일도, 돈도 기록하기", "Record tasks and money"],
    ["사진·인터뷰, 쓰기 전 3가지", "Three checks before using photos and interviews"],
    ["모르는 것 → 확인할 질문", "Unknowns → questions to investigate"],
    ["울릉에서 찾는 사업 소재", "Finding business topics on Ulleungdo"],
    ["나의 자원과 관심 업무", "My resources and work interests"],
    ["먼저 만날 고객 고르기", "Choosing customers to meet first"],
    ["고객의 한 장면 적기", "Describing a customer situation"],
    ["아이디어 2개 만들기", "Developing two ideas"],
    ["아이디어마다 확인 질문 1개", "One research question per idea"],
    ["아이디어 1분 소개", "A one-minute idea introduction"],
    ["10분 쉬어가기 · 사업 메모 준비", "Ten-minute break · prepare business notes"],
    ["사업 메모 ① 고객과 경험", "Business notes: customers and experience"],
    ["사업 메모 ② 제작과 운영", "Business notes: production and operations"],
    ["두 사업의 고객과 경험", "Customers and experiences for two businesses"],
    ["두 사업의 제작과 운영", "Production and operations for two businesses"],
    ["사업 메모, 한 칸에 한 줄", "One line per business-note field"],
    ["견적 확인 → 다음 할 일", "From a quote to the next task"],
    ["고칠 점 + 확인할 방법", "What to fix and how to check it"],
    ["초안은 AI, 판단은 우리", "AI drafts; we decide"],
    ["좋은 요청의 재료", "Ingredients of a good request"],
    ["우리 팀의 AI 요청문 만들기", "Writing our team's AI prompt"],
    ["그대로 써도 될까?", "Can we publish it unchanged?"],
    ["공개 전, 최종 확인", "Final checks before publication"],
    ["10분 쉬어가기 · 역할 정하기 준비", "Ten-minute break · prepare role selection"],
    ["우리 회사의 역할 지도", "Our company's role map"],
    ["보드게임팀의 할 일", "Board game team tasks"],
    ["매거진팀의 할 일", "Magazine team tasks"],
    ["본부의 할 일", "Coordination team tasks"],
    ["두 사업을 돕는 공통 지원", "Shared support for both businesses"],
    ["주 역할 1개 + 지원 역할 1개", "One lead role and one support role"],
    ["보고할 내용 3가지", "Three things to report"],
    ["맡고 싶은 일 적기", "Write down the work you want to do"],
    ["희망 역할 모둠으로 이동", "Join your preferred role group"],
    ["할 일마다 담당자 정하기", "Assign an owner to every task"],
    ["빠진 일, 몰린 일 점검", "Check missing and overloaded tasks"],
    ["우리 팀의 운영 약속 5가지", "Five working agreements"],
    ["우리 팀 계획, 2분 소개", "Our team plan in two minutes"],
    ["다음은 고객·지역 조사", "Next: customer and local research"],
  ],
};

export function lesson2Slides(english: boolean) {
  return lesson2.titles.map((titles, index) => ({
    title: titles[english ? 1 : 0],
    summary: "",
    image: `/assets/materials/ulleung-high-2026-09-19/slide-${String(index + 1).padStart(2, "0")}.webp`,
  }));
}
