type Text = readonly [string, string];
type Example = { id: string; track: "general" | "local"; title: Text; customer: Text; problem: Text; offer: Text; revenue: Text; trial: Text; check: Text };

export const startupExamples: Example[] = [
  {
    id: "club-tools", track: "general",
    title: ["동아리 출석·과제 정리 도구", "Club attendance and assignment organizer"],
    customer: ["여러 모임을 관리하는 동아리 지도교사와 운영자", "Teachers and organizers managing several club groups"],
    problem: ["출석은 종이, 과제는 채팅방에 남아 미제출자를 따로 확인해야 한다는 상황을 가정합니다.", "Assume attendance is recorded on paper while assignments arrive in chat, requiring a separate check for missing work."],
    offer: ["모임별 출석과 과제 제출 여부를 한 화면에 모으고, 확인할 항목을 표시합니다.", "Show attendance and assignment status together, highlighting items that need checking."],
    revenue: ["운영기관에 모임 단위 이용료를 받는 안입니다. 무료 문서 도구보다 편리한지 먼저 확인합니다.", "A proposed per-group fee paid by the institution, after checking whether it improves on free document tools."],
    trial: ["앱을 만들기 전에 가상 명단으로 화면을 그리고 지도교사에게 기존 관리 방식과 비교해달라고 요청합니다.", "Draw screens with fictional names and ask a teacher to compare them with the current workflow before building an app."],
    check: ["학생 개인정보를 어떻게 보호할지, 실제 구매 결정자는 누구인지 확인해야 합니다.", "Check student privacy requirements and who can actually authorize a purchase."],
  },
  {
    id: "shared-equipment", track: "general",
    title: ["공용 물품 대여·반납 관리", "Shared equipment checkout tracker"],
    customer: ["카메라·충전기·공구 등을 함께 쓰는 동아리나 작은 기관", "Clubs or small organizations sharing cameras, chargers or tools"],
    problem: ["누가 물건을 빌렸고 언제 돌려주는지 몰라 다음 사용자가 기다리는 상황을 가정합니다.", "Assume people do not know who borrowed an item or when it will return, delaying the next user."],
    offer: ["물품별 대여 상태와 반납 예정일을 확인하고 다음 사용을 신청하는 도구입니다.", "A tool showing item availability and return dates, with a request for the next use."],
    revenue: ["기관별 설치·초기 등록 비용이나 관리 이용료를 검토할 수 있습니다.", "Consider an institution setup fee or a management subscription."],
    trial: ["가상 물품 10개로 대여 기록표를 만들고, 사용자가 대여와 반납을 혼자 기록할 수 있는지 살펴봅니다.", "Create a checkout sheet for ten fictional items and test whether users can record loans and returns unaided."],
    check: ["기존 예약 도구와의 차이, 분실·파손 시 책임 범위는 별도로 정해야 합니다.", "Clarify differences from existing booking tools and responsibility for loss or damage."],
  },
  {
    id: "shop-notices", track: "general",
    title: ["작은 가게의 공지 작성 도우미", "Notice-writing assistant for small shops"],
    customer: ["휴무·예약·품절 안내를 직접 작성하는 가게 운영자", "Shop owners who write their own closure, booking and stock notices"],
    problem: ["같은 안내를 여러 채널에 맞춰 다시 쓰고 날짜나 연락처를 빠뜨리는 상황을 가정합니다.", "Assume owners rewrite notices for different channels and sometimes omit dates or contact details."],
    offer: ["운영자가 입력한 사실만으로 안내문 초안을 만들고 날짜·시간 등 빠진 항목을 표시합니다.", "Draft notices only from facts entered by the owner and flag missing dates or times."],
    revenue: ["안내문 묶음 제작비 또는 월 이용료를 제안할 수 있습니다. 지불 의사는 확인되지 않았습니다.", "Possible pricing is a notice package or monthly fee; willingness to pay has not been established."],
    trial: ["가상의 휴무 안내 3개를 작성하고 운영자에게 수정할 부분과 걸리는 시간을 물어봅니다.", "Draft three fictional closure notices and ask owners what they would change and how long editing takes."],
    check: ["무료 AI와 비교해 어떤 시간을 줄이는지 확인하고, 게시 전 운영자가 내용을 검토하게 합니다.", "Check what time it saves compared with free AI tools and require owner review before publishing."],
  },
  {
    id: "ulleung-magazine", track: "local",
    title: ["울릉매거진 · 학생들이 전하는 울릉도", "Ulleung Magazine · the island through students’ reporting"],
    customer: ["독자는 울릉도 여행을 준비하는 사람입니다. 비용을 낼 고객으로는 가게·숙소·체험 운영자와 지역 홍보 콘텐츠가 필요한 기관을 검토합니다. 독자와 구매자를 구분해 기획합니다.", "Readers are people planning a trip to Ulleungdo. Potential paying customers include shops, accommodation and experience operators, and organizations needing local promotional content. Plan separately for readers and buyers."],
    problem: ["방문객은 장소 정보뿐 아니라 실제 이동 방법과 지역 사람의 이야기를 알고 싶고, 작은 가게는 소개 글과 사진을 꾸준히 만들기 어렵다는 가정에서 시작합니다. 방문객과 운영자를 만나 이 불편이 실제로 있는지 확인합니다.", "Start with two assumptions: visitors want practical routes and local stories as well as listings, while small businesses struggle to produce regular articles and photos. Check both assumptions with visitors and operators."],
    offer: ["학생들이 장소·가게·생활 이야기를 취재하고 글·사진·짧은 영상으로 소개하는 관광 플랫폼입니다. 기사마다 위치, 이동 방법, 확인 날짜를 적고 관련 장소를 지도와 코스로 묶습니다. 처음에는 웹 매거진으로 시작하고, 수요를 확인한 뒤 검색·지도·제휴 문의 기능을 늘립니다.", "A tourism platform where students report on places, businesses and everyday life through articles, photos and short videos. Include location, directions and verification dates, then group related places into maps and routes. Start with a web magazine and add search, mapping and partnership inquiries after testing demand."],
    revenue: ["일반 기사는 무료로 읽게 하고, 가게·숙소의 소개 콘텐츠 제작비나 기관의 지역 홍보물 제작비를 받는 안입니다. 독자가 생긴 뒤 광고·제휴 수익을 검토합니다. 유료 소개는 광고·협찬임을 구분하고, 가격과 실제 구매 의사는 별도로 확인합니다.", "Keep editorial articles free and consider charging businesses or institutions for commissioned content. Explore advertising or partnerships after building readership. Clearly label paid coverage, and test pricing and willingness to pay separately."],
    trial: ["학생 팀이 동의받은 가게 인터뷰 1편, 장소 소개 1편, 짧은 여행 코스 1편을 만들어 한 페이지에 모읍니다. 취재·촬영·편집·사실 확인 역할을 나누고, 여행객에게 빠진 정보를 묻습니다. 가게에는 유료 제작을 맡길 의향과 조건을 확인하고, 조회수와 실제 문의를 따로 기록합니다.", "Publish one consented shop interview, one place guide and one short itinerary on a single page. Assign reporting, photography, editing and fact-checking roles. Ask visitors what is missing and businesses whether they would commission content and on what terms. Track views separately from actual inquiries."],
    check: ["울릉도의 장소와 주민 취재가 콘텐츠의 핵심이라는 점에서 로컬 분야를 검토할 수 있습니다. 지역에서 운영한다는 이유만으로 분류하지는 않습니다. 사진·인터뷰 공개 동의, 정보 갱신, 취재 안전, 학생의 연락처 보호를 확인하고 유료 계약과 대금 수령은 학교·보호자와 운영 방식을 먼저 정합니다. 아직 운영 중인 플랫폼이나 계약이 있는 사업으로 쓰지 않습니다.", "Local places and resident reporting are central to this proposal, which is why a local-track discussion is relevant—not simply its address. Check publication consent, updates, reporting safety and protection of student contact details. Agree with the school and guardians on contracts and payments before paid work. Do not describe this proposal as an operating platform or a contracted business."],
  },
  {
    id: "island-walk", track: "local",
    title: ["주민 이야기와 함께 걷는 울릉도 코스", "Ulleungdo walks with residents’ stories"],
    customer: ["지역의 생활 이야기를 듣고 싶은 여행객", "Visitors interested in stories about local life"],
    problem: ["명소 위치는 찾아도 주민의 생활과 연결된 설명은 얻기 어렵다는 가정에서 출발합니다.", "Start with the assumption that visitors can find landmarks but struggle to learn how they relate to local life."],
    offer: ["주민과 함께 확인한 이야기, 이동 경로, 쉬는 장소를 묶은 소규모 체험을 기획합니다.", "Plan a small-group experience combining resident-verified stories, a walking route and rest stops."],
    revenue: ["참가비를 받고 해설에 참여한 주민에게 비용을 지급하는 안입니다. 가격과 배분은 협의가 필요합니다.", "A proposed participation fee with payment to resident guides; pricing and revenue sharing require agreement."],
    trial: ["실제 모집 전 종이 코스 안내를 만들고 주민에게 이야기의 정확성과 참여 의사를 확인합니다.", "Before recruiting participants, draft a paper route and ask residents to verify the stories and discuss participation."],
    check: ["통행 가능 여부, 날씨에 따른 취소 기준, 안전 관리와 운영에 필요한 조건을 확인해야 합니다.", "Check route access, weather cancellation rules, safety arrangements and operating requirements."],
  },
  {
    id: "local-gift", track: "local",
    title: ["울릉도 생산자 소개가 담긴 선물 구성", "Gift sets introducing Ulleungdo producers"],
    customer: ["생산자와 제품의 특징을 알고 지역 상품을 사고 싶은 방문객", "Visitors who want to understand local products and their producers before buying"],
    problem: ["지역 상품의 생산 과정과 차이를 비교하기 어렵다는 상황을 가정합니다.", "Assume buyers find it difficult to compare how local goods are made and what makes them different."],
    offer: ["협의한 생산자의 상품에 확인된 생산 과정과 사용 방법을 담은 소개 카드를 함께 구성합니다.", "Pair an agreed producer’s goods with cards explaining verified production details and uses."],
    revenue: ["구성 상품 판매 또는 생산자와 협의한 판매 수수료를 검토합니다. 실제 공급 계약은 없는 예시입니다.", "Consider gift-set sales or an agreed sales commission. No supply contract exists for this example."],
    trial: ["실물을 구매·판매하기 전에 종이 구성안 두 가지를 만들고 방문객에게 선택 이유를 물어봅니다.", "Make two paper mockups before purchasing or selling stock and ask visitors why they prefer one."],
    check: ["생산자 동의, 공급 가격, 배송·보관 조건과 상품별 표시 기준을 확인해야 합니다.", "Check producer consent, supply costs, shipping and storage conditions, and product labeling requirements."],
  },
  {
    id: "island-kit", track: "local",
    title: ["울릉도 관찰 활동 키트", "Ulleungdo observation activity kit"],
    customer: ["울릉도 현장학습을 준비하는 교사와 가족", "Teachers and families planning a field trip to Ulleungdo"],
    problem: ["방문 장소는 정했지만 학생이 무엇을 관찰하고 기록할지 준비하기 어렵다는 가정입니다.", "Assume a visit is planned but it is difficult to prepare observation and recording tasks for students."],
    offer: ["공개된 관찰 장소를 바탕으로 질문 카드와 기록지를 만듭니다. 동식물을 채집하지 않는 활동을 설계합니다.", "Create question cards and worksheets for publicly accessible observation sites, without collecting wildlife."],
    revenue: ["학급용 키트 판매나 기관용 수업자료 제작비를 검토합니다.", "Consider classroom kit sales or a fee for producing institution-specific learning materials."],
    trial: ["한 장소용 기록지 1장을 만들고 교사에게 질문의 난이도와 수업 활용 방법을 검토받습니다.", "Make one worksheet for one location and ask a teacher to review its difficulty and classroom use."],
    check: ["자료의 사실관계, 사진 사용 권리, 현장 출입·보호 규정을 확인해야 합니다.", "Check factual accuracy, photo permissions, site access and conservation rules."],
  },
];
